-- Run in the Supabase SQL editor. Everything (including users) is rolled back.
begin;
create temporary table nec_test_results(test text, passed boolean);
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); e uuid; r uuid; data jsonb; failed boolean;
begin
 insert into auth.users(id,email) values(a,'nec-test-a@example.invalid'),(b,'nec-test-b@example.invalid');
 insert into public.nec_admins(user_id) values(a);
 perform set_config('request.jwt.claim.sub',a::text,true);
 data:=jsonb_build_object('title','Test event','description','A transactional test event.','venue','Nowshera test venue','category','Workshop','starts_at',now()+interval '2 days','capacity',1,'status','published');
 e:=(public.nec_api('save',data)->>'id')::uuid;
 r:=(public.nec_api('register',jsonb_build_object('id',e))->>'id')::uuid;
 insert into nec_test_results values('Registration saved',r is not null);
 failed:=false;begin perform public.nec_api('register',jsonb_build_object('id',e));exception when others then failed:=sqlerrm like '%already%';end;
 insert into nec_test_results values('Duplicate prevented',failed);
 perform set_config('request.jwt.claim.sub',b::text,true);
 failed:=false;begin perform public.nec_api('register',jsonb_build_object('id',e));exception when others then failed:=sqlerrm like '%full%';end;
 insert into nec_test_results values('Capacity enforced',failed);
 insert into nec_test_results values('Other user cannot see registration',jsonb_array_length(public.nec_api('my'))=0);
 failed:=false;begin perform public.nec_api('cancel',jsonb_build_object('id',r));exception when others then failed:=sqlerrm like '%not found%';end;
 insert into nec_test_results values('Other user cannot cancel registration',failed);
 failed:=false;begin perform public.nec_api('admin_list');exception when others then failed:=sqlerrm like '%Administrator%';end;
 insert into nec_test_results values('Attendee cannot access admin',failed);
 perform set_config('request.jwt.claim.sub',a::text,true);
 failed:=false;begin perform public.nec_api('save',data||jsonb_build_object('id',e,'capacity',0));exception when others then failed:=sqlerrm like '%Capacity%';end;
 insert into nec_test_results values('Capacity reduction blocked',failed);
 perform public.nec_api('cancel',jsonb_build_object('id',r));
 insert into nec_test_results values('Cancellation releases capacity',(public.nec_api('detail',jsonb_build_object('id',e))->>'registered')::int=0);
 perform set_config('request.jwt.claim.sub',b::text,true);
 perform public.nec_api('register',jsonb_build_object('id',e));
 insert into nec_test_results values('Released seat can be reserved',(public.nec_api('detail',jsonb_build_object('id',e))->>'registered')::int=1);
 perform set_config('request.jwt.claim.sub',a::text,true);
 failed:=false;begin perform public.nec_api('delete',jsonb_build_object('id',e));exception when others then failed:=sqlerrm like '%history%';end;
 insert into nec_test_results values('Registration history retained',failed);
 perform public.nec_api('save',data||jsonb_build_object('id',e,'status','cancelled'));
 failed:=false;begin perform public.nec_api('register',jsonb_build_object('id',e));exception when others then failed:=sqlerrm like '%no longer%';end;
 insert into nec_test_results values('Cancelled event rejects registrations',failed);
 update public.nec_events set status='published',starts_at=now()-interval '1 day' where id=e;
 failed:=false;begin perform public.nec_api('register',jsonb_build_object('id',e));exception when others then failed:=sqlerrm like '%no longer%';end;
 insert into nec_test_results values('Past event rejects registrations',failed);
 update public.nec_events set status='draft',starts_at=now()+interval '1 day' where id=e;
 insert into nec_test_results values('Draft excluded from discovery',not exists(select 1 from jsonb_array_elements(public.nec_api('list')) x where x->>'id'=e::text));
 perform set_config('request.jwt.claim.sub','',true);
 failed:=false;begin perform public.nec_api('my');exception when others then failed:=sqlerrm like '%sign in%';end;
 insert into nec_test_results values('Anonymous private access rejected',failed);
end $$;
select * from nec_test_results;
select bool_and(passed) as all_passed,count(*) as total_tests from nec_test_results;
rollback;
