'use strict';
const $=s=>document.querySelector(s), cfg=window.NEC_CONFIG;
let session;try{session=JSON.parse(sessionStorage.getItem('nec_session')||'null')}catch{session=null}
let profile=null, events=[], registrations=[], attendees=[], category='All events', query='', adminStatus='all', preview=false, loaded=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Intl.DateTimeFormat('en-PK',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Karachi'}).format(new Date(v));
const time=v=>new Intl.DateTimeFormat('en-PK',{hour:'numeric',minute:'2-digit',timeZone:'Asia/Karachi'}).format(new Date(v));
const day=v=>new Intl.DateTimeFormat('en',{day:'2-digit',timeZone:'Asia/Karachi'}).format(new Date(v));
const month=v=>new Intl.DateTimeFormat('en',{month:'short',timeZone:'Asia/Karachi'}).format(new Date(v));
const isFuture=e=>new Date(e.starts_at)>new Date();
const state=e=>e.status==='published'?(isFuture(e)?(e.registered>=e.capacity?'full':'available'):'past'):e.status;
const badge=s=>`<span class="badge ${esc(s)}">${esc(s)}</span>`;
function setSession(data){session=data?.access_token?data:null;if(session)sessionStorage.setItem('nec_session',JSON.stringify(session));else sessionStorage.removeItem('nec_session')}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),5000)}
async function request(path,options={},retry=true){
 if(preview)throw Error('The Python backend has not been connected to this preview yet.');
 let response;try{response=await fetch(cfg.API_BASE+path,{...options,headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.access_token}:{}),...options.headers}})}catch{throw Error('Cannot connect. Please check your connection and try again.')}
 if(response.status===401&&session?.refresh_token&&retry){
  const res=await fetch(cfg.API_BASE+'/api/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});
  if(res.ok){setSession(await res.json());return request(path,options,false)}setSession(null);profile=null;account();throw Error('Your session expired. Please sign in again.');
 }
 if(options.raw&&response.ok)return response;
 let body;try{body=await response.json()}catch{throw Error('The event service is not available. Please try again later.')}
 if(!response.ok){const d=body.detail;throw Error(Array.isArray(d)?d.map(e=>e.msg).join('. '):d||'Unable to complete your request')}
 return body;
}
const post=(path,data={})=>request(path,{method:'POST',body:JSON.stringify(data)});
async function publicEvents(){
 if(!preview)return request('/api/events');
 const res=await fetch(cfg.SUPABASE_URL+'/rest/v1/rpc/nec_api',{method:'POST',headers:{apikey:cfg.SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({operation:'list',payload:{}})});
 if(!res.ok)throw Error('Events could not be loaded. Please try again.');return res.json();
}
function account(){const mail=session?.user?.email||'Your account';$('#account').innerHTML=session?`<span class="account-name">${esc(mail)}</span><button class="button ghost small" data-action="logout">Sign out</button>`:'<button class="button small" data-action="login">Sign in ↗</button>'}
function modal(label,content){$('#modal-label').textContent=label;$('#modal-content').innerHTML=content;$('#modal').showModal()}
function close(){ $('#modal').close() }
function navigate(path){history.pushState({},'',path);query='';category='All events';route();window.scrollTo(0,0)}
function intro(kicker,title,subtitle,action=''){return `<div class="intro"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function empty(title,text,action=''){return `<div class="empty"><div class="empty-icon" aria-hidden="true">▦</div><h3>${title}</h3><p>${text}</p>${action}</div>`}
function errorBox(error){return `<div class="error-box" role="alert">${esc(error.message)} <button class="text-button" data-action="reload">Try again</button></div>`}
async function route(){
 const path=location.pathname;
 document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===(path==='/'?'/events':path)));
 document.title=(path.startsWith('/admin')?'Admin dashboard':path==='/registrations'?'My registrations':'Discover events')+' | Nowshera Events Co.';
 if(path.startsWith('/admin'))return adminPage();
 if(path==='/registrations')return myPage();
 if(path.startsWith('/events/')&&path.split('/')[2]){await discover();try{const e=await request('/api/events/'+encodeURIComponent(path.split('/')[2]));showDetail(e)}catch(e){notify(e.message)}return}
 return discover();
}
async function discover(){
 $('#main').innerHTML=intro('Discover & connect','Good things happen together.','Workshops, ideas and experiences. Find your next event in Nowshera.','<div class="location">⌖ &nbsp; Nowshera, Pakistan</div>')+
 `<section class="feature-strip" aria-label="About our events"><div><h2>Your city. Your next experience.</h2><p>Make space for something new.</p></div><div class="strip-item"><span class="strip-icon" aria-hidden="true">◷</span><div><strong>A place to learn</strong><p>Workshops & thoughtful conversations</p></div></div><div class="strip-item"><span class="strip-icon" aria-hidden="true">◎</span><div><strong>A community to meet</strong><p>Local connections that last</p></div></div></section>
 <div class="toolbar"><div class="filters" aria-label="Event categories">${['All events','Workshop','Seminar','Community'].map(c=>`<button class="chip ${c===category?'selected':''}" aria-pressed="${c===category}" data-category="${c}">${c==='All events'?c:c==='Community'?'Community':c+'s'}</button>`).join('')}</div><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Search events or venues" aria-label="Search events or venues" value="${esc(query)}"></label></div>
 <div class="section-line"><h2>Upcoming events <span id="count" class="count">—</span></h2><span>Discover • Reserve • Show up</span></div><section id="event-list" class="grid" aria-live="polite"><p class="loading">Loading upcoming events…</p></section>`;
 try{events=await publicEvents();drawEvents()}catch(e){$('#event-list').innerHTML=errorBox(e)}
}
function drawEvents(){let list=events.filter(e=>(category==='All events'||e.category===category)&&[e.title,e.venue,e.description].join(' ').toLowerCase().includes(query.toLowerCase()));$('#count').textContent=list.length;
 $('#event-list').innerHTML=list.length?list.map(e=>`<article class="event-card"><div class="card-top"><div class="date-block">${day(e.starts_at)}<small>${month(e.starts_at)}</small></div><span class="category">${esc(e.category)}</span></div><div class="card-body"><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="meta">◷ <span>${date(e.starts_at)} · ${time(e.starts_at)} PKT</span></div><div class="meta">⌖ <span>${esc(e.venue)}</span></div><div class="card-bottom">${state(e)==='full'?badge('full'):`<span><strong>${Math.max(0,e.capacity-e.registered)}</strong> places left</span>`}<button class="text-button" data-detail="${e.id}">View event ↗</button></div></div></article>`).join(''):empty(query||category!=='All events'?'No matching events':'Your next experience is on its way.',query||category!=='All events'?'Try another search or choose a different category.':'There are no published upcoming events yet. Check back soon for workshops, seminars and community gatherings.',query||category!=='All events'?'<button class="button ghost" data-action="reset">Clear filters</button>':'<button class="button ghost" data-action="reload">Refresh events</button>');
}
function showDetail(e){
 const s=state(e);modal('EVENT DETAILS',`<div class="eyebrow">${esc(e.category)}</div><h2 style="margin-top:12px">${esc(e.title)}</h2>${badge(s)}<p class="detail-description">${esc(e.description)}</p><div class="detail-grid"><div><small>Date & time · PKT</small><strong>${date(e.starts_at)} · ${time(e.starts_at)}</strong></div><div><small>Venue</small><strong>${esc(e.venue)}</strong></div><div><small>Total capacity</small><strong>${e.capacity} people</strong></div><div><small>Available places</small><strong>${Math.max(0,e.capacity-e.registered)}</strong></div></div><div id="form-error" class="form-error" role="alert"></div><div class="form-footer"><button class="button ghost" data-action="close">Close</button><button class="button" data-register="${e.id}" ${s!=='available'?'disabled':''}>${s==='available'?(session?'Reserve my place':'Sign in to register'):esc(s)}</button></div>`);
}
function authForm(mode='login',admin=false){const signup=mode==='signup';return `<div class="eyebrow">${admin?'Operations access':'Welcome to the community'}</div><h2 style="margin-top:12px">${signup?'Create your account':admin?'Administrator sign in':'Welcome back.'}</h2><p class="muted">${signup?'Find your next experience and keep your plans in one place.':admin?'Sign in with your authorized administrator account.':'Sign in to reserve a place and manage your registrations.'}</p><form id="auth-form" data-mode="${mode}">${signup?'<label class="field"><span>Full name</span><input name="name" autocomplete="name" required maxlength="100" placeholder="Your full name"></label>':''}<label class="field"><span>Email address</span><input type="email" name="email" autocomplete="email" required maxlength="254" placeholder="you@example.com"></label><label class="field"><span>Password</span><input name="password" type="password" autocomplete="${signup?'new-password':'current-password'}" minlength="8" maxlength="128" required placeholder="At least 8 characters"></label><div id="form-error" class="form-error" role="alert"></div><button class="button" style="width:100%" type="submit">${signup?'Create account':'Sign in'} ↗</button></form>${!admin?`<p class="note">${signup?'Already have an account?':'New here?'} <button class="text-button" data-auth="${signup?'login':'signup'}">${signup?'Sign in':'Create an account'}</button></p>`:''}`}
function login(){modal('YOUR ACCOUNT',authForm())}
async function myPage(){
 $('#main').innerHTML=intro('Your plans','My registrations','Your reserved places, all in one place.','<a class="button ghost" href="/events" data-nav>Discover events ↗</a>')+'<div id="registration-list" aria-live="polite"></div>';
 if(!session){$('#registration-list').innerHTML='<div class="auth-card">'+authForm()+'</div>';return}
 $('#registration-list').innerHTML='<div class="loading">Loading your registrations…</div>';
 try{registrations=await request('/api/registrations');$('#registration-list').innerHTML=registrations.length?registrations.map(r=>{let e=r.event;const can=r.status==='active'&&isFuture(e)&&!['cancelled','completed'].includes(e.status);return `<article class="registration"><div class="date-block">${day(e.starts_at)}<small>${month(e.starts_at)}</small></div><div class="registration-info">${badge(r.status==='cancelled'?'cancelled':e.status==='cancelled'?'cancelled':e.status==='completed'?'completed':!isFuture(e)?'past':'confirmed')}<h3>${esc(e.title)}</h3><div class="meta">${date(e.starts_at)} · ${time(e.starts_at)} PKT · ${esc(e.venue)}</div><small class="muted">Booking ${esc(r.id.slice(0,8).toUpperCase())}</small></div><div class="actions">${can?`<button class="button ghost small" data-cancel="${r.id}">Cancel registration</button>`:''}</div></article>`}).join(''):empty('Your calendar has room for something good.','Browse upcoming events and reserve your first place.','<a class="button" href="/events" data-nav>Explore events ↗</a>')}catch(e){$('#registration-list').innerHTML=errorBox(e)}
}
async function adminPage(){
 $('#main').innerHTML=intro('Operations','Event dashboard','A clear view of your events and the people joining them.')+'<div id="admin-body"></div>';
 if(!session){$('#admin-body').innerHTML='<div class="auth-card">'+authForm('login',true)+'</div>';return}
 $('#admin-body').innerHTML='<p class="loading">Checking administrator access…</p>';
 try{profile=await request('/api/me');if(!profile.is_admin){$('#admin-body').innerHTML=empty('Administrator access required','Your account is an attendee account. Contact the event organizer if you need operations access.','<a class="button" href="/events" data-nav>Browse events</a>');return}
 const [stats,list]=await Promise.all([request('/api/admin/stats'),request('/api/admin/events')]);events=list;
 $('#admin-body').innerHTML=`<div class="stats">${[['Total events',stats.total_events,'All event statuses'],['Upcoming events',stats.upcoming_events,'Published & open for discovery'],['Active registrations',stats.registrations,'Across all events'],['Available places',stats.available_places,'At upcoming published events']].map(([label,value,note])=>`<div class="stat"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('')}</div><section class="panel"><div class="section-line" style="margin-top:0"><h2>Manage events</h2><button class="button" data-action="new-event">＋ Create event</button></div><div class="toolbar"><label class="search"><span aria-hidden="true">⌕</span><input id="admin-search" type="search" placeholder="Search events" aria-label="Search events"></label><select id="admin-status" class="admin-select" aria-label="Filter by event status"><option value="all">All statuses</option>${['draft','published','cancelled','completed'].map(s=>`<option>${s}</option>`).join('')}</select></div><div id="admin-events"></div></section>`;drawAdmin();
 }catch(e){$('#admin-body').innerHTML=errorBox(e)}
}
function drawAdmin(){const q=$('#admin-search')?.value.toLowerCase()||'',status=$('#admin-status')?.value||'all';const list=events.filter(e=>e.title.toLowerCase().includes(q)&&(status==='all'||e.status===status));$('#admin-events').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Event</th><th>Schedule · PKT</th><th>Status</th><th>Registrations</th><th>Actions</th></tr></thead><tbody>${list.map(e=>`<tr><td><strong>${esc(e.title)}</strong><small>${esc(e.venue)}</small></td><td class="nowrap">${date(e.starts_at)}<small>${time(e.starts_at)}</small></td><td>${badge(e.status)}</td><td>${e.registered} / ${e.capacity}<div class="capacity-meter"><span style="width:${Math.min(100,e.registered/e.capacity*100)}%"></span></div></td><td><div class="actions"><button class="text-button" data-edit="${e.id}">Edit</button><button class="text-button" data-attendees="${e.id}">Attendees</button><button class="text-button" data-delete="${e.id}">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`:empty(events.length?'No matching events':'Start with your first event.',events.length?'Try a different search or status filter.':'Create a draft, add the details, and publish when you are ready.','<button class="button" data-action="new-event">＋ Create event</button>')}
function eventForm(e={}){const datetime=e.starts_at?new Date(new Date(e.starts_at).getTime()+5*3600000).toISOString().slice(0,16):'';modal(e.id?'EDIT EVENT':'CREATE EVENT',`<h2>${e.id?'Make every detail count.':'Bring people together.'}</h2><p class="muted">Schedule times are in Pakistan Standard Time (UTC+5).</p><form id="event-form"><input type="hidden" name="id" value="${e.id||''}"><div class="form-grid"><label class="field wide"><span>Event title</span><input name="title" required minlength="3" maxlength="160" value="${esc(e.title||'')}" placeholder="Give your event a clear name"></label><label class="field wide"><span>Description</span><textarea name="description" required minlength="10" maxlength="10000" placeholder="What can attendees expect?">${esc(e.description||'')}</textarea></label><label class="field wide"><span>Venue</span><input name="venue" required minlength="3" maxlength="240" value="${esc(e.venue||'')}" placeholder="Venue name and address"></label><label class="field"><span>Date & time · PKT</span><input name="starts_at" type="datetime-local" required value="${datetime}"></label><label class="field"><span>Capacity</span><input name="capacity" type="number" min="1" max="100000" step="1" required value="${e.capacity||30}"></label><label class="field"><span>Category</span><select name="category">${['Workshop','Seminar','Community'].map(s=>`<option ${s===e.category?'selected':''}>${s}</option>`).join('')}</select></label><label class="field"><span>Status</span><select name="status">${['draft','published','cancelled','completed'].map(s=>`<option ${s===(e.status||'draft')?'selected':''}>${s}</option>`).join('')}</select></label></div><div id="form-error" class="form-error" role="alert"></div><div class="form-footer"><button class="button ghost" type="button" data-action="close">Cancel</button><button class="button" type="submit">Save event</button></div></form>`)}
function confirmAction(label,text,type,id){modal(label,`<h2>${label}</h2><p class="muted">${text}</p><div id="form-error" class="form-error" role="alert"></div><div class="form-footer"><button class="button ghost" data-action="close">Keep it</button><button class="button danger" data-confirm="${type}" data-id="${id}">Confirm ${type==='cancel'?'cancellation':'deletion'}</button></div>`)}
async function attendeeView(id){modal('ATTENDEE LIST','<p class="loading">Loading attendees…</p>');try{attendees=await request(`/api/admin/events/${id}/attendees`);const e=events.find(x=>x.id===id);$('#modal-content').innerHTML=`<h2>${esc(e?.title||'Event attendees')}</h2><div class="toolbar"><label class="search"><span aria-hidden="true">⌕</span><input id="attendee-search" type="search" aria-label="Search attendees" placeholder="Search name or email"></label><button class="button ghost small" data-export="${id}">Export CSV ↓</button></div><select id="attendee-status" aria-label="Filter registration status"><option value="all">All registrations</option><option value="active">Active only</option><option value="cancelled">Cancelled only</option></select><div id="attendee-list"></div>`;drawAttendees()}catch(e){$('#modal-content').innerHTML=errorBox(e)}}
function drawAttendees(){let q=$('#attendee-search').value.toLowerCase(),s=$('#attendee-status').value;const rows=attendees.filter(r=>(s==='all'||r.status===s)&&(r.name+' '+r.email).toLowerCase().includes(q));$('#attendee-list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Attendee</th><th>Status</th><th>Booking</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong><small>${esc(r.email)}</small></td><td>${badge(r.status)}</td><td>${esc(r.id.slice(0,8))}</td></tr>`).join('')}</tbody></table></div>`:'<p class="loading">No attendees match this view.</p>'}
async function runButton(button,fn){button.disabled=true;try{await fn()}catch(e){const err=$('#modal[open] #form-error');if(err)err.textContent=e.message;else notify(e.message)}finally{button.disabled=false}}
document.addEventListener('click',async event=>{
 const nav=event.target.closest('[data-nav]');if(nav){event.preventDefault();navigate(nav.getAttribute('href'));return}
 const b=event.target.closest('button');if(!b)return;
 if(b.dataset.category){category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)});drawEvents();return}
 if(b.dataset.auth){const content=authForm(b.dataset.auth);if($('#modal').open)$('#modal-content').innerHTML=content;else $('.auth-card').innerHTML=content;return}
 if(b.dataset.detail){showDetail(events.find(e=>e.id===b.dataset.detail));return}
 if(b.dataset.register){if(!session){close();login();return}return runButton(b,async()=>{const r=await post(`/api/events/${b.dataset.register}/register`);close();notify('Your place is confirmed! Booking '+r.id.slice(0,8).toUpperCase());await route()})}
 if(b.dataset.edit){eventForm(events.find(e=>e.id===b.dataset.edit));return}
 if(b.dataset.cancel){confirmAction('Cancel your registration?','Your place will be released for another attendee.','cancel',b.dataset.cancel);return}
 if(b.dataset.delete){confirmAction('Delete this event?','This permanently deletes an event with no registration history. Events with registrations must be cancelled instead.','delete',b.dataset.delete);return}
 if(b.dataset.confirm){return runButton(b,async()=>{await post(b.dataset.confirm==='cancel'?`/api/registrations/${b.dataset.id}/cancel`:`/api/admin/events/${b.dataset.id}/delete`);close();notify(b.dataset.confirm==='cancel'?'Registration cancelled. Your place has been released.':'Event deleted.');await route()})}
 if(b.dataset.attendees)return attendeeView(b.dataset.attendees);
 if(b.dataset.export)return runButton(b,async()=>{const res=await request(`/api/admin/events/${b.dataset.export}/export`,{raw:true});const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='attendees.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Attendee list exported.')});
 switch(b.dataset.action){case'login':login();break;case'close':close();break;case'new-event':eventForm();break;case'reload':if($('#modal').open)close();await route();break;case'reset':query='';category='All events';await discover();break;case'logout':return runButton(b,async()=>{await post('/api/auth/logout');setSession(null);profile=null;account();notify('You are signed out.');route()})}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;drawEvents()}if(e.target.id==='admin-search')drawAdmin();if(e.target.id==='attendee-search')drawAttendees()});
document.addEventListener('change',e=>{if(e.target.id==='admin-status')drawAdmin();if(e.target.id==='attendee-status')drawAttendees()});
document.addEventListener('submit',async event=>{
 const form=event.target;if(!['auth-form','event-form'].includes(form.getAttribute('id')))return;event.preventDefault();const button=form.querySelector('[type="submit"]');form.querySelector('#form-error').textContent='';button.disabled=true;
 try{const data=Object.fromEntries(new FormData(form));if(form.getAttribute('id')==='auth-form'){
 const result=await post('/api/auth/'+form.dataset.mode,data);if(!result.access_token){form.innerHTML='<div class="empty-icon">✉</div><h3>Check your inbox.</h3><p>Confirm your email address using the link from Supabase, then come back to sign in.</p><button type="button" class="button" data-auth="login">Back to sign in</button>';return}
 setSession(result);account();if($('#modal').open)close();notify('You are signed in.');await route();
 }else{data.capacity=Number(data.capacity);data.starts_at=new Date(data.starts_at+':00+05:00').toISOString();data.id=data.id||null;await post('/api/admin/events',data);close();notify('Event saved.');await adminPage()}
 }catch(e){form.querySelector('#form-error').textContent=e.message}finally{button.disabled=false}
});
window.addEventListener('popstate',route);
async function init(){account();try{const r=await fetch(cfg.API_BASE+'/api/health');const d=await r.json();if(d.backend!=='python')throw Error()}catch{preview=true;$('#preview-note').hidden=false}loaded=true;await route()}
init();
